- alias: Licht an 45min vor Sonnenuntergang
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'person.patrick_tracker_2'
        state: 'home'
      - condition: state
        entity_id: 'person.jenny_tracker_2'
        state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 200
        color_name: sandybrown
    - service: switch.turn_on
      entity_id: switch.strom_wohnzimmer

- alias: Licht aus 90min nach Sonnenaufgang
  trigger:
  - event: sunrise
    offset: 01:00:00
    platform: sun
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.living_room
  - service: switch.turn_off
    entity_id: switch.strom_wohnzimmer

- alias: Schlafzimmer Licht an
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'person.patrick_tracker_2'
        state: 'home'
      - condition: state
        entity_id: 'person.jenny_tracker_2'
        state: 'home'
  action:
  - service: switch.turn_on
    entity_id: switch.strom_schlafzimmer


- alias: Schlafzimmer Licht aus
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.strom_schlafzimmer

- alias: Unter der Woche, morgens Licht an
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 255
        color_name: lightcyan
    - service: switch.turn_on
      entity_id: switch.strom_wohnzimmer

- alias: Sonos Bad Play/Pause Toggle
  trigger:
    platform: webhook
    webhook_id: sonos_bathroom_toggle
  action:
    - service: media_player.media_play_pause
      entity_id: media_player.bathroom

- alias: Sonos Bad Pause
  trigger:
    platform: webhook
    webhook_id: sonos_bathroom_pause
  action:
    - service: media_player.media_pause
      entity_id: media_player.bathroom
