- alias: Licht an 45min vor Sonnenuntergang
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition: []
  action:
    - service: light.turn_on
      entity_id: group.licht_philips
      data:
        brightness: 200
        color_name: sandybrown

- alias: Licht aus 90min nach Sonnenaufgang
  trigger:
  - event: sunrise
    offset: 01:30:00
    platform: sun
  condition: []
  action:
  - service: light.turn_off
    entity_id: group.licht_philips

- alias: Unter der Woche, morgens Licht an
  trigger:
    platform: time
    at: '05:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      entity_id: group.licht_philips 
      data:
        brightness: 255
        color_name: lightcyan

- alias: Push Nachricht wenn Hochbeet über 25 Grad
  trigger:
    platform: numeric_state
    entity_id: sensor.hochbeet_temperature_max_last_12h
    above: 25
  action:
    - service: notify.pushover_notification
      data:
        title: "Hochbeet sehr warm!"
        message: |
          Balkon:
          - {{ states.sensor.netatmo_outdoor_temperature.state }} °C
          Hochbeet:
          - {{ states.sensor.hochbeet_temperature.state }} °C ({{ states.sensor.hochbeet_temperature_max_last_12h.state }} °C max/12h)
          - {{ states.sensor.hochbeet_moisture.state }} % Feuchtigkeit ({{ states.sensor.hochbeet_moisture_min_last_12h.state }} % min/12h)
          - {{ states.sensor.hochbeet_light_intensity.state }} lx
        data:
          sound: pianobar
          priority: 0
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.push_nachricht_wenn_hochbeet_uber_25_grad.attributes.last_triggered | default(0)) | int > 14400)}}'

- alias: Push Nachricht an Patrick wenn zuhause und Beet zu trocken war
  trigger:
    - platform: numeric_state
      entity_id: sensor.hochbeet_moisture_min_last_12h
      below: 17
    - platform: state
      entity_id: person.patrick
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'person.patrick'
        state: 'home'
      - condition: numeric_state
        entity_id: 'sensor.hochbeet_moisture_min_last_12h'
        below: 17
      - condition: template
        value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.push_nachricht_an_patrick_wenn_zuhause_und_beet_zu_trocken_war.attributes.last_triggered | default(0)) | int > 14400 )}}'
  action:
    - service: notify.pushover_notification
      data:
        title: "Hochbeet giessen"
        message: |
          Balkon:
          - {{ states.sensor.netatmo_outdoor_temperature.state }} °C
          Hochbeet:
          - {{ states.sensor.hochbeet_temperature.state }} °C ({{ states.sensor.hochbeet_temperature_max_last_12h.state }} °C max/12h)
          - {{ states.sensor.hochbeet_moisture.state }} % Feuchtigkeit ({{ states.sensor.hochbeet_moisture_min_last_12h.state }} % min/12h)
          - {{ states.sensor.hochbeet_light_intensity.state }} lx
        data:
          sound: pianobar
          priority: 0
