homeassistant:
  name: !secret ha_instance_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 415
  unit_system: metric
  time_zone: Europe/Zurich
  customize: !include customize.yaml

lovelace:
  mode: yaml

default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://ha:3218

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

influxdb:
  host: !secret influxdb_host
  port: 8086
  database: ha
  default_measurement: state

notify:
  - name: pushover_notification
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: lametric_notification
    platform: lametric
    lifetime: 20
    icon: a7956
    cycles: 3
    priority: info

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.3.246
      - 192.168.3.127
    interval_seconds: 30
    consider_home: 7

mqtt:
  broker: 192.168.3.51

frontend:
  themes: !include themes.yaml

person: !include people.yaml
sensor:
  - platform: yr
  - platform: rest
    resource: http://192.168.3.142/report
    value_template: "{{ value_json.temperature | round(1) }}"
    name: "Temperatur Wand TV Rack"
    unit_of_measurement: °C
    scan_interval: 180
  - platform: rest
    resource: http://192.168.3.233/report
    value_template: "{{ value_json.temperature | round(1) }}"
    name: "Temperatur Wand Büro Server"
    unit_of_measurement: °C
    scan_interval: 180
  - platform: rest
    resource: http://192.168.3.221/report
    value_template: "{{ value_json.temperature | round(1) }}"
    name: "Temperatur Wand Büro Patrick"
    unit_of_measurement: °C
    scan_interval: 180
  - platform: rest
    resource: http://192.168.3.237/report
    value_template: "{{ value_json.temperature | round(1) }}"
    name: "Temperatur Wand Küche"
    unit_of_measurement: °C
    scan_interval: 180
  - platform: rest
    resource: http://192.168.3.101/report
    value_template: "{{ value_json.temperature | round(1) }}"
    name: "Temperatur Wand WoZi rechts"
    unit_of_measurement: °C
    scan_interval: 180
  - platform: rest
    resource: http://192.168.3.211/report
    value_template: "{{ value_json.temperature | round(1) }}"
    name: "Temperatur Wand Balkon"
    unit_of_measurement: °C
    scan_interval: 180
  - platform: influxdb
    host: !secret influxdb_host
    port: 8086
    queries:
      - name: Hochbeet temperature max last 12h
        unit_of_measurement: '°C'
        value_template: '{{ value | round(1) }}'
        group_function: max
        where: '"entity_id" = ''hochbeet_temperature'' and time > now() - 12h'
        measurement: '"°C"'
        field: value
        database: ha
      - name: Hochbeet moisture min last 12h
        unit_of_measurement: '%'
        value_template: '{{ value | round(1) }}'
        group_function: min
        where: '"entity_id" = ''hochbeet_moisture'' and time > now() - 12h'
        measurement: '"%"'
        field: value
        database: ha
      - name: Hochbeet moisture last value
        unit_of_measurement: '%'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''hochbeet_moisture'''
        measurement: '"%"'
        field: value
        database: ha
      - name: Hochbeet temperature last value
        unit_of_measurement: '°C'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''hochbeet_temperature'''
        measurement: '"°C"'
        field: value
        database: ha
      - name: Hochbeet light intensity last value
        unit_of_measurement: 'lx'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''hochbeet_light_intensity'''
        measurement: '"lx"'
        field: value
        database: ha
      - name: Hochbeet conductivity last value
        unit_of_measurement: 'µS'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''hochbeet_conductivity'''
        measurement: '"µS/cm"'
        field: value
        database: ha
      - name: Hochbeet battery last value
        unit_of_measurement: '%'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''hochbeet_battery'''
        measurement: '"%"'
        field: value
        database: ha
      - name: Jolokia Chili moisture last value
        unit_of_measurement: '%'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''jolokia_chili_moisture'''
        measurement: '"%"'
        field: value
        database: ha
      - name: Jolokia Chili temperature last value
        unit_of_measurement: '°C'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''jolokia_chili_temperature'''
        measurement: '"°C"'
        field: value
        database: ha
      - name: Jolokia Chili light intensity last value
        unit_of_measurement: 'lx'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''jolokia_chili_light_intensity'''
        measurement: '"lx"'
        field: value
        database: ha
      - name: Jolokia Chili conductivity last value
        unit_of_measurement: 'µS'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''jolokia_chili_conductivity'''
        measurement: '"µS/cm"'
        field: value
        database: ha
      - name: Jolokia Chili battery last value
        unit_of_measurement: '%'
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"entity_id" = ''jolokia_chili_battery'''
        measurement: '"%"'
        field: value
        database: ha

plant:
  Jolokia Chili Plant:
    sensors:
      moisture: sensor.jolokia_chili_moisture_last_value
      battery: sensor.jolokia_chili_battery_last_value
      temperature: sensor.jolokia_chili_temperature_last_value
      conductivity: sensor.jolokia_chili_conductivity_last_value
      brightness: sensor.jolokia_chili_light_intensity_last_value
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15
  Hochbeet Epic Mega Plant:
    sensors:
      moisture: sensor.hochbeet_moisture_last_value
      battery: sensor.hochbeet_battery_last_value
      temperature: sensor.hochbeet_temperature_last_value
      conductivity: sensor.hochbeet_conductivity_last_value
      brightness: sensor.hochbeet_light_intensity_last_value
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15

switch:
  - platform: mystrom
    host: 192.168.3.142
    name: Strom TV Rack
    scan_interval: 10
  - platform: mystrom
    host: 192.168.3.233
    name: Strom Büro Server
    scan_interval: 10
  - platform: mystrom
    host: 192.168.3.221
    name: Strom Büro Patrick
    scan_interval: 10
  - platform: mystrom
    host: 192.168.3.237
    name: Strom Küche
    scan_interval: 10
  - platform: mystrom
    host: 192.168.3.101
    name: Strom WoZi rechts
    scan_interval: 10
  - platform: mystrom
    host: 192.168.3.211
    name: Strom Balkon
    scan_interval: 10

lametric:
  client_id:  !secret lametric_client_id
  client_secret: !secret lametric_client_secret
