homeassistant:
  name: !secret ha_instance_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 415
  unit_system: metric
  time_zone: Europe/Zurich
  customize: !include customize.yaml

lovelace:
  mode: yaml

default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://ha:3218

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

homematic:
  interfaces:
    rf:
      host: 192.168.3.230
      username: !secret homematic_ccu2_user
      password: !secret homematic_ccu2_password

#influxdb:
#  host: !secret influxdb_host
#  port: 8086
#  database: ha
#  default_measurement: state

notify:
  - name: pushover_notification
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: lametric_notification
    platform: lametric
    lifetime: 20
    icon: a7956
    cycles: 3
    priority: info

#device_tracker:
#  - platform: nmap_tracker
#    hosts:
#      - 192.168.3.246
#      - 192.168.3.127
#    interval_seconds: 30
#    consider_home: 7

mqtt:
  broker: 192.168.3.51

#frontend:
#  themes: !include themes.yaml

person: !include people.yaml

#sensor:
#  - platform: rest
#    resource: http://192.168.3.139/status
#    value_template: "{{ value_json.tmp.tC }}"
#    name: "Temperatur Zimmer Patrick"
#    unit_of_measurement: °C
#    scan_interval: 900

#sensor:
#  - platform: rest
#    resource: http://192.168.3.142/report
#    value_template: "{{ value_json.temperature | round(1) }}"
#    name: "Temperatur Wand TV Rack"
#    unit_of_measurement: °C
#    scan_interval: 180
#  - platform: rest
#    resource: http://192.168.3.233/report
#    value_template: "{{ value_json.temperature | round(1) }}"
#    name: "Temperatur Wand Büro Server"
#    unit_of_measurement: °C
#    scan_interval: 180
#  - platform: rest
#    resource: http://192.168.3.221/report
#    value_template: "{{ value_json.temperature | round(1) }}"
#    name: "Temperatur Wand Büro Patrick"
#    unit_of_measurement: °C
#    scan_interval: 180
#  - platform: rest
#    resource: http://192.168.3.237/report
#    value_template: "{{ value_json.temperature | round(1) }}"
#    name: "Temperatur Wand Küche"
#    unit_of_measurement: °C
#    scan_interval: 180
#  - platform: rest
#    resource: http://192.168.3.101/report
#    value_template: "{{ value_json.temperature | round(1) }}"
#    name: "Temperatur Wand WoZi rechts"
#    unit_of_measurement: °C
#    scan_interval: 180
#  - platform: rest
#    resource: http://192.168.3.238/report
#    value_template: "{{ value_json.temperature | round(1) }}"
#    name: "Temperatur Schreibtisch Jenny"
#    unit_of_measurement: °C
#    scan_interval: 180
#  - platform: rest
#    resource: http://192.168.3.211/report
#    value_template: "{{ value_json.temperature | round(1) }}"
#    name: "Temperatur Tannenbaum"
#    unit_of_measurement: °C
#    scan_interval: 180
#  - platform: influxdb
#    host: !secret influxdb_host
#    port: 8086
#    queries:
#      - name: Hochbeet temperature max last 12h
#        unit_of_measurement: '°C'
#        value_template: '{{ value | round(1) }}'
#        group_function: max
#        where: '"entity_id" = ''hochbeet_temperature'' and time > now() - 12h'
#        measurement: '"°C"'
#        field: value
#        database: ha
#      - name: Hochbeet moisture min last 12h
#        unit_of_measurement: '%'
#        value_template: '{{ value | round(1) }}'
#        group_function: min
#        where: '"entity_id" = ''hochbeet_moisture'' and time > now() - 12h'
#        measurement: '"%"'
#        field: value
#        database: ha

#plant:
#  Jolokia Chili Plant:
#    sensors:
#      moisture: sensor.jolokia_chili_moisture
#      battery: sensor.jolokia_chili_battery
#      temperature: sensor.jolokia_chili_temperature
#      conductivity: sensor.jolokia_chili_conductivity
#      brightness: sensor.jolokia_chili_light_intensity
#    min_moisture: 20
#    max_moisture: 60
#    min_battery: 20
#    min_conductivity: 500
#    min_temperature: 15
#  Hochbeet Epic Mega Plant:
#    sensors:
#      moisture: sensor.hochbeet2_moisture
#      battery: sensor.hochbeet2_battery
#      temperature: sensor.hochbeet2_temperature
#      conductivity: sensor.hochbeet2_conductivity
#      brightness: sensor.hochbeet2_light_intensity
#    min_moisture: 20
#    max_moisture: 60
#    min_battery: 20
#    min_conductivity: 500
#    min_temperature: 15
#  Karotten:
#    sensors:
#      moisture: sensor.karotten_moisture
#      battery: sensor.karotten_battery
#      temperature: sensor.karotten_temperature
#      conductivity: sensor.karotten_conductivity
#      brightness: sensor.karotten_light_intensity
#    min_moisture: 20
#    max_moisture: 60
#    min_battery: 20
#    min_conductivity: 500
#    min_temperature: 15
#  Lilien:
#    sensors:
#      moisture: sensor.lilien_moisture
#      battery: sensor.lilien_battery
#      temperature: sensor.lilien_temperature
#      conductivity: sensor.lilien_conductivity
#      brightness: sensor.lilien_light_intensity
#    min_moisture: 20
#    max_moisture: 60
#    min_battery: 20
#    min_conductivity: 500
#    min_temperature: 15
#  Lavendel:
#    sensors:
#      moisture: sensor.lavendel_moisture
#      battery: sensor.lavendel_battery
#      temperature: sensor.lavendel_temperature
#      conductivity: sensor.lavendel_conductivity
#      brightness: sensor.lavendel_light_intensity
#    min_moisture: 20
#    max_moisture: 60
#    min_battery: 20
#    min_conductivity: 500
#    min_temperature: 15
#  Zami:
#    sensors:
#      moisture: sensor.zami_moisture
#      battery: sensor.zami_battery
#      temperature: sensor.zami_temperature
#      conductivity: sensor.zami_conductivity
#      brightness: sensor.zami_light_intensity
#    min_moisture: 20
#    max_moisture: 60
#    min_battery: 20
#    min_conductivity: 500
#    min_temperature: 15
#
#  - platform: miflora
#    mac: 'C4:7C:8D:67:65:DC'
#    name: Lavendel
#    scan_interval: 3600
#    median: 3
#  - platform: miflora
#    mac: 'C4:7C:8D:6A:A7:68'
#    name: Jolokia Chili
#    scan_interval: 3600
#    median: 3
#  - platform: miflora
#    mac: 'C4:7C:8D:6A:64:F9'
#    name: Karotten
#    scan_interval: 3600
#    median: 3
#  - platform: miflora
#    mac: 'C4:7C:8D:6A:A6:81'
#    name: Lilien
#    scan_interval: 3600
#    median: 3
#  - platform: miflora
#    mac: 'C4:7C:8D:6A:A4:BD'
#    name: Hochbeet2
#    scan_interval: 3600
#    median: 3
#  - platform: miflora
#    mac: 'C4:7C:8D:6A:B7:AE'
#    name: Zami
#    scan_interval: 3600
#    median: 3

#switch:
#  - platform: mystrom
#    host: 192.168.3.142
#    name: Strom TV Rack
#    scan_interval: 30
#  - platform: mystrom
#    host: 192.168.3.233
#    name: Strom Büro Server
#    scan_interval: 30
#  - platform: mystrom
#    host: 192.168.3.221
#    name: Strom Büro Patrick
#    scan_interval: 30
#  - platform: mystrom
#    host: 192.168.3.237
#    name: Strom Küche
#    scan_interval: 30
#  - platform: mystrom
#    host: 192.168.3.101
#    name: Strom WoZi rechts
#    scan_interval: 30
#  - platform: mystrom
#    host: 192.168.3.211
#    name: Strom Tannenbaum
#    scan_interval: 30
#  - platform: mystrom
#    host: 192.168.3.238
#    name: Strom Jenny Desk
#    scan_interval: 30

lametric:
  client_id:  !secret lametric_client_id
  client_secret: !secret lametric_client_secret
