homeassistant:
  name: !secret ha_instance_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 415
  unit_system: metric
  time_zone: Europe/Zurich
  customize: !include customize.yaml

lovelace:
  mode: yaml

default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

recorder:
  purge_keep_days: 5

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

homematic:
  interfaces:
    rf:
      host: 192.168.3.230
      username: !secret homematic_ccu2_user
      password: !secret homematic_ccu2_password
    ip:
      host: 192.168.3.230
      username: !secret homematic_ccu2_user
      password: !secret homematic_ccu2_password
      port: 2010

logger:
  default: info

notify:
  - name: pushover_notification
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: lametric_notification
    platform: lametric
    lifetime: 20
    icon: a7956
    cycles: 3
    priority: info

person: !include people.yaml

switch:
  - platform: mystrom
    host: 192.168.3.211
    name: Strom Schlafzimmer
    scan_interval: 30
  - platform: mystrom
    host: 192.168.3.221
    name: Strom Patrick
    scan_interval: 30
  - platform: mystrom
    host: 192.168.3.142
    name: Strom Wohnzimmer
    scan_interval: 30

lametric:
  client_id:  !secret lametric_client_id
  client_secret: !secret lametric_client_secret

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan Wohnzimmer
    host: 192.168.3.198
    token: !secret xiaomi_fan_wozi
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan Patrick
    host: 192.168.3.207
    token: !secret xiaomi_fan_patrick
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan Jenny
    host: 192.168.3.213
    token: !secret xiaomi_fan_jenny

influxdb:
  api_version: 2
  ssl: false
  host: nas.pjhome
  port: 49153
  bucket: pjhome
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  max_retries: 3
  default_measurement: state
  exclude:
    entities:
      - sun.sun
    domains:
      - automation
      - group
