light.hgrp_0000000030:
    hidden: true

light.hgrp_0000000014:
    hidden: true

binary_sensor.oeq1982192_state:
  friendly_name: Wohnzimmer
  icon: mdi:window-maximize

binary_sensor.oeq1982179_state:
  friendly_name: Zimmer Patrick
  icon: mdi:window-maximize

binary_sensor.oeq1987700_state:
  friendly_name: Bad
  icon: mdi:window-maximize

binary_sensor.oeq1984662_state:
  friendly_name: Zimmer Jenny
  icon: mdi:window-maximize

binary_sensor.oeq1986380_state:
  friendly_name: Schlafzimmer
  icon: mdi:window-maximize

binary_sensor.oeq0686091_state:
  friendly_name: Schiebet체r Balkon
  icon: mdi:door

binary_sensor.oeq1986334_state:
  friendly_name: Eingangst체r
  icon: mdi:door

light.stripe:
  friendly_name: Le Stripe

# Patrick Desk
switch.00101be9935f81:
  friendly_name: Patrick Desk Steckdose
sensor.00101Be9935f81_current:
  friendly_name: Patrick Desk Stromst채rke
  unit_of_measurement: mA
sensor.00101Be9935f81_energy_counter:
  friendly_name: Patrick Desk Gesamtverbrauch
  unit_of_measurement: Wh
sensor.00101Be9935f81_frequency:
  friendly_name: Patrick Desk Frequenz
  unit_of_measurement: Hz
sensor.00101Be9935f81_power:
  friendly_name: Patrick Desk Verbrauch
  unit_of_measurement: W
sensor.00101Be9935f81_voltage:
  friendly_name: Patrick Desk Spannung
  unit_of_measurement: V

# Chilis
switch.00101be9935eef:
  friendly_name: Chilis Steckdose
sensor.00101be9935eef_current:
  friendly_name: Chilis Stromst채rke
  unit_of_measurement: mA
sensor.00101be9935eef_energy_counter:
  friendly_name: Chilis Gesamtverbrauch
  unit_of_measurement: Wh
sensor.00101be9935eef_frequency:
  friendly_name: Chilis Frequenz
  unit_of_measurement: Hz
sensor.00101be9935eef_power:
  friendly_name: Chilis Verbrauch
  unit_of_measurement: W
sensor.00101be9935eef_voltage:
  friendly_name: Chilis Spannung
  unit_of_measurement: V
