licht_philips:
  name: Philips Funzeln
  entities:
    - light.living_room

licht_wohnzimmer:
  name: Philips Funzeln
  entities:
    - light.living_room

sound_sonos:
  name: Sonos b00m
  entities:
    - media_player.bathroom
    - media_player.jenny
    - media_player.kitchen
    - media_player.patrick
    - media_player.playbar_tv

netatmo_sensors:
  name: Netatmo
  entities:
    - sensor.netatmo_indoor_temperature
    - sensor.netatmo_indoor_humidity
    - sensor.netatmo_indoor_co2
    - sensor.netatmo_indoor_noise
    - sensor.netatmo_indoor_pressure
    - sensor.netatmo_indoor_wifi
    - sensor.netatmo_outdoor_temperature
    - sensor.netatmo_outdoor_humidity
    - sensor.netatmo_outdoor_battery_percent
    - sensor.netatmo_outdoor_battery
    - sensor.netatmo_outdoor_radio