icon: 'mdi:clock'
title: Automatisierungen
badges: []
cards:
  - title: Automatisierung
    type: entities
    entities:
      - entity: automation.licht_an_45min_vor_sonnenuntergang
      - entity: automation.unter_der_woche_morgens_licht_an
      - entity: automation.licht_aus_90min_nach_sonnenaufgang
      - entity: automation.schlafzimmer_licht_an
      - entity: automation.schlafzimmer_licht_aus
  - title: People
    type: entities
    entities:
      - entity: person.patrick_tracker_2
      - entity: person.jenny_tracker_2
