icon: 'mdi:speaker'
title: Media
badges: []
cards:
  - entities:
      - media_player.bathroom
      - media_player.jenny
      - media_player.kitchen
      - media_player.patrick
      - media_player.playbar_tv
    type: entities
    title: Sound