icon: 'mdi:flower'
panel: true
title: Pflanzen
badges: []
cards:
  - entities:
      - sensor.hochbeet_conductivity_last_value
      - sensor.hochbeet_light_intensity_last_value
      - sensor.hochbeet_moisture_last_value
      - sensor.hochbeet_temperature_last_value
    type: history-graph
