icon: 'mdi:flower'
panel: true
title: Pflanzen
badges: []
cards:
  - entities:
      - sensor.hochbeet_conductivity
      - sensor.hochbeet_light_intensity
      - sensor.hochbeet_moisture
      - sensor.hochbeet_temperature
      - sensor.jolokia_chili_conductivity
      - sensor.jolokia_chili_light_intensity
      - sensor.jolokia_chili_moisture
      - sensor.jolokia_chili_temperature
      - sensor.karotten_conductivity
      - sensor.karotten_light_intensity
      - sensor.karotten_moisture
      - sensor.karotten_temperature
    type: history-graph
