icon: 'mdi-ceiling-light'
title: Licht
badges: []
cards:
  - title: Wohnzimmer
    type: entities
    show_header_toggle: true
    entities:
      - light.tvlinks
      - light.tvrechts
  - title: Essbereich
    type: entities
    show_header_toggle: true
    entities:
      - light.esstisch
  - title: Schlafzimmer
    type: entities
    show_header_toggle: true
    entities:
      - switch.strom_schlafzimmer
  - title: Patrick
    type: entities
    show_header_toggle: true
    entities:
      - light.stripe
  - title: Jenny
    type: entities
    show_header_toggle: true
    entities:
      - light.jenny1
      - light.jenny2
