icon: 'mdi:flower'
panel: true
title: Pflanzen
badges: []
cards:
  - entities:
      - sensor.hochbeet_conductivity
      - sensor.hochbeet_light_intensity
      - sensor.hochbeet_moisture
      - sensor.hochbeet_temperature
      - sensor.jolokia_chili_conductivity
      - sensor.jolokia_chili_light_intensity
      - sensor.jolokia_chili_moisture
      - sensor.jolokia_chili_temperature
      - sensor.karotten_conductivity
      - sensor.karotten_light_intensity
      - sensor.karotten_moisture
      - sensor.karotten_temperature
      - sensor.lilien_conductivity
      - sensor.lilien_light_intensity
      - sensor.lilien_moisture
      - sensor.lilien_temperature
      - sensor.lavendel_conductivity
      - sensor.lavendel_light_intensity
      - sensor.lavendel_moisture
      - sensor.lavendel_temperature
      - sensor.zami_conductivity
      - sensor.zami_light_intensity
      - sensor.zami_moisture
      - sensor.zami_temperature
    type: history-graph
