icon: 'mdi:thermometer'
panel: true
title: Klima
badges:
  - sensor.netatmo_wetterarsch_temperature
  - sensor.netatmo_wetterarsch_humidity
  - sensor.netatmo_wetterarsch_co2
cards:
  - entities:
      - sensor.netatmo_wetterarsch_temperature
      - sensor.netatmo_wetterarsch_humidity
      - sensor.netatmo_wetterarsch_co2
      - sensor.netatmo_wetterarsch_noise
      - sensor.netatmo_wetterarsch_pressure
      - sensor.netatmo_wetterarsch_bedroom_co2
      - sensor.netatmo_wetterarsch_bedroom_humidity
      - sensor.netatmo_wetterarsch_bedroom_temperature
      - sensor.netatmo_wetterarsch_outdoor_temperature
      - sensor.netatmo_wetterarsch_outdoor_humidity
    type: history-graph