icon: 'mdi-lightbulb'
panel: true
title: Licht
badges: []
cards:
  - entities:
    - title: Wohnzimmer Sofa
      type: light
      entity: light.sofa
    - title: Wohnzimmer links
      type: light
      entity: light.wohnzimmer_links
    - title: Wohnzimmer rechts
      type: light
      entity: light.wohnzimmer_rechts
    - title: Wohnzimmer Zami
      type: light
      entity: light.zami
