icon: 'mdi:thermometer'
panel: true
title: Klima
badges:
  - sensor.netatmo_outdoor_humidity
  - sensor.netatmo_indoor_co2
  - sensor.netatmo_outdoor_battery
cards:
  - entities:
      - sensor.netatmo_indoor_temperature
      - sensor.netatmo_indoor_humidity
      - sensor.netatmo_indoor_co2
      - sensor.netatmo_indoor_noise
      - sensor.netatmo_indoor_pressure
      - sensor.netatmo_indoor_wifi
      - sensor.netatmo_outdoor_temperature
      - sensor.netatmo_outdoor_humidity
      - sensor.netatmo_outdoor_battery
      - sensor.netatmo_outdoor_radio
    type: history-graph
