title: Home
icon: 'mdi:home-assistant'
panel: false
path: default_view
badges:
  - sun.sun
cards:
  - type: plant-status
    entity: plant.hochbeet_epic_mega_plant
  - type: plant-status
    entity: plant.jolokia_chili_plant
