- alias: Hochbeet conductivity to mqtt
  trigger:
    platform: event
    event_type: signal_received
    event_data: {'entity_id': 'sensor.hochbeet_conductivity'}
  action:
    service: mqtt.publish
    data:
      topic: "home/sensors/"
      payload_template: "{{ states.sensor.hochbeet_conductivity.state }}"
- alias: Hochbeet light intesnity to mqtt
  trigger:
    platform: event
    event_type: signal_received
    event_data: {'entity_id': 'sensor.hochbeet_light_intensity'}
  action:
    service: mqtt.publish
    data:
      topic: "home/sensors/"
      payload_template: "{{ states.sensor.hochbeet_light_intensity.state }}"
- alias: Hochbeet moisture to mqtt
  trigger:
    platform: event
    event_type: signal_received
    event_data: {'entity_id': 'sensor.hochbeet_moisture'}
  action:
    service: mqtt.publish
    data:
      topic: "home/sensors/"
      payload_template: "{{ states.sensor.hochbeet_moisture.state }}"
- alias: Hochbeet temperature to mqtt
  trigger:
    platform: event
    event_type: signal_received
    event_data: {'entity_id': 'sensor.hochbeet_temperature'}
  action:
    service: mqtt.publish
    data:
      topic: "home/sensors/"
      payload_template: "{{ states.sensor.hochbeet_temperature.state }}"

- alias: Restart HA
  trigger:
    platform: time
    at: "01:33:37"
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
    - service: homeassistant.restart