homeassistant:
  name: !secret ha_instance_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 415
  unit_system: metric
  time_zone: Europe/Zurich
  customize: !include customize.yaml

lovelace:
  mode: yaml

default_config:

automation: !include automations.yaml

mqtt:
  broker: 192.168.3.51

influxdb:
  host: !secret influxdb_host
  port: 8086
  database: ha
  default_measurement: state

sensor:
  - platform: miflora
    mac: 'C4:7C:8D:67:65:DC'
    name: Hochbeet
    force_update: true
    scan_interval: 900
    median: 3
  - platform: yr
