homeassistant:
  name: !secret ha_instance_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 415
  unit_system: metric
  time_zone: Europe/Zurich
  customize: !include customize.yaml

lovelace:
  mode: yaml

default_config:

automation: !include automations.yaml

influxdb:
  host: !secret influxdb_host
  port: 8086
  database: ha
  default_measurement: state

sensor:
  - platform: miflora
    mac: 'C4:7C:8D:67:65:DC'
    name: Hochbeet
    force_update: true
    scan_interval: 1800
    median: 3
  - platform: miflora
    mac: 'C4:7C:8D:6A:A7:68'
    name: Jolokia Chili
    force_update: true
    scan_interval: 1800
    median: 3

plant:
  Jolokia Chili Plant:
    sensors:
      moisture: sensor.jolokia_chili_moisture
      battery: sensor.jolokia_chili_battery
      temperature: sensor.jolokia_chili_temperature
      conductivity: sensor.jolokia_chili_conductivity
      brightness: sensor.jolokia_chili_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15
  Hochbeet Epic Mega Plant:
    sensors:
      moisture: sensor.hochbeet_moisture
      battery: sensor.hochbeet_battery
      temperature: sensor.hochbeet_temperature
      conductivity: sensor.hochbeet_conductivity
      brightness: sensor.hochbeet_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15